### ISSUE TITLE
Intel HD Graphics 4000 glXCreateContextAttribsARB Failed

### ISSUE THREAD

**Issue by zhedye** [floooh/sokol#1161]
I am running an example Sokol program on linux: [https://github.com/floooh/sokol-samples … ube-sapp.c](https://github.com/floooh/sokol-samples/blob/master/sapp/cube-sapp.c)

I get this error:

```
[sapp][panic][id:35] ../../sokol/sokol_app.h:10351:0:
	LINUX_GLX_CREATE_CONTEXT_FAILED: Failed to create GL context via glXCreateContextAttribsARB
```

The corresponding glfw example works.

Is there another way to create a window with sokol for this old graphics card?

`inxi -Ga`:

```
Graphics:
  Device-1: Intel 3rd Gen Core processor Graphics vendor: Apple driver: i915
    v: kernel arch: Gen-7 process: Intel 22nm built: 2012-13 ports:
    active: LVDS-1 empty: DP-1, DP-2, DP-3, HDMI-A-1, HDMI-A-2, HDMI-A-3,
    VGA-1 bus-ID: 00:02.0 chip-ID: 8086:0166 class-ID: 0300
  Device-2: Apple FaceTime HD Camera (Built-in) driver: uvcvideo type: USB
    rev: 2.0 speed: 480 Mb/s lanes: 1 mode: 2.0 bus-ID: 1-1.1:3
    chip-ID: 05ac:8509 class-ID: 0e02 serial: DJHC8806HWDH7FL0
  Display: unspecified server: X.Org v: 21.1.14 driver: X:
    loaded: modesetting alternate: fbdev,intel,vesa dri: crocus gpu: i915
    display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1280x800 s-dpi: 96 s-size: 338x211mm (13.31x8.31")
    s-diag: 398mm (15.69")
  Monitor-1: LVDS-1 model: Apple Color LCD built: 2009 res: 1280x800 hz: 60
    dpi: 114 gamma: 1.2 size: 286x179mm (11.26x7.05") diag: 337mm (13.3")
    ratio: 16:10 modes: 1280x800
  API: EGL v: 1.5 hw: drv: intel crocus platforms: device: 0 drv: crocus
    device: 1 drv: swrast gbm: drv: crocus surfaceless: drv: crocus x11:
    drv: crocus inactive: wayland
  API: OpenGL v: 4.5 compat-v: 4.2 vendor: intel mesa v: 24.2.7-arch1.1
    glx-v: 1.4 direct-render: yes renderer: Mesa Intel HD Graphics 4000 (IVB
    GT2) device-ID: 8086:0166 memory: 1.46 GiB unified: yes
```
